name: Deploy to Linode Compute Instance

on:
  push:
    branches: ["master"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run Tests
        run: yarn test-pipeline

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thoughtspring:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull and Run Docker Image on Linode Remote Server
        uses: appleboy/ssh-action@master
        env:
          LOCAL_PORT: ${{ secrets.LOCAL_PORT }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_DAEMON: ${{ secrets.EMAIL_DAEMON }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: LOCAL_PORT,NEXT_PUBLIC_RECAPTCHA_SITE_KEY,RECAPTCHA_SECRET_KEY,EMAIL_ACCOUNT,EMAIL_DAEMON,EMAIL_PASSWORD
          script: |
            export envArray=($LOCAL_PORT $NEXT_PUBLIC_RECAPTCHA_SITE_KEY $RECAPTCHA_SECRET_KEY $EMAIL_ACCOUNT $EMAIL_DAEMON $EMAIL_PASSWORD) \
            && docker pull thoughtspring/thoughtspring \
            && if [[ -z $(docker container ls -a | grep "thoughtspring") ]]; \
            then echo "No container found. Starting thoughtspring container..."; \
            else docker stop thoughtspring && docker rm thoughtspring; \
            fi \
            && docker run -d -p "${envArray[0]}":3000 --name thoughtspring --restart always \
            -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY="${envArray[1]}" \
            -e RECAPTCHA_SECRET_KEY="${envArray[2]}" \
            -e EMAIL_ACCOUNT="${envArray[3]}" \
            -e EMAIL_DAEMON="${envArray[4]}" \
            -e EMAIL_PASSWORD="${envArray[5]}" \
            thoughtspring/thoughtspring \
            && exit \
            && exit 0;